#!/usr/bin/env bash
#
# mk_hdr
#
# create an HDR image from a series of input images


# https://de.mathworks.com/help/images/ref/makehdr.html
# http://linuxdarkroom.tassy.net/hdr-creation-script/


# https://towardsdatascience.com/a-simple-hdr-implementation-on-opencv-python-2325dbd9c650
# https://docs.opencv.org/3.4/d3/db7/tutorial_hdr_imaging.html
# https://github.com/fthaler/rawhdr
# https://github.com/wzinke/EnhanceHDR
# https://colour-hdri.readthedocs.io/en/latest/manual.html
# https://learnopencv.com/high-dynamic-range-hdr-imaging-using-opencv-cpp-python/

# https://openexr.readthedocs.io/en/latest/
# https://jcelaya.github.io/hdrmerge/
# http://pfstools.sourceforge.net/
# https://www.radiance-online.org/
# https://wiki.panotools.org/HDR_workflow_with_hugin

# https://hdr.gerhard-obermayr.com/software/freie-software/
# https://hdr.gerhard-obermayr.com/technik/tonwert/tone-mapping/
