#!/usr/bin/env bash
#
# focus_stack
#


# https://patdavid.net/2013/01/focus-stacking-macro-photos-enfuse/
# https://web.archive.org/web/20160917212243/http://photoblog.edu-perez.com/2009/01/greater-depth-field-macro.html
